---
- name: Configure Git to use Fedora Keyring
  hosts: localhost
  become: yes

  tasks:
    - name: Ensure libsecret and git-credential-libsecret are installed
      dnf:
        name:
          - libsecret
          - seahorse
          - git-credential-libsecret
        state: present

    - name: Configure Git to use libsecret credential helper
      command: git config --global credential.helper /usr/libexec/git-core/git-credential-libsecret
      args:
        creates: ~/.gitconfig

    - name: Verify Git credential helper configuration
      command: git config --global credential.helper
      register: result

    - name: Print Git credential helper configuration
      debug:
        msg: "{{ result.stdout }}"

