---
- name: Konfigurieren von Symlinks, Git-Repository aktualisieren und Programminstallation
  hosts: localhost
  vars:
    home_dir: "{{ ansible_env.HOME }}"
    dotfiles_repo: "git@github.com:schwarz-christoph/.dotfiles.git"
    dotfiles_dest: "{{ home_dir }}/.dotfiles"
    symlink_list:        
        - { src: "{{ home_dir }}/.dotfiles/.config/fontconfig/fonts.conf", path: "{{ home_dir }}/.config/fontconfig/fonts.conf" }
        - { src: "{{ home_dir }}/.dotfiles/.config/ranger/rc.conf", path: "{{ home_dir }}/.config/ranger/rc.conf" }
        - { src: "{{ home_dir }}/.dotfiles/.config/ranger/commands.py", path: "{{ home_dir }}/.config/ranger/commands.py" }
        - { src: "{{ home_dir }}/.dotfiles/.config/ranger/plugins", path: "{{ home_dir }}/.config/ranger/plugins" }
        - { src: "{{ home_dir }}/.dotfiles/.config/tmuxinator/lldb.yml", path: "{{ home_dir }}/.config/tmuxinator/lldb.yml" }
        - { src: "{{ home_dir }}/.dotfiles/.bashrc", path: "{{ home_dir }}/.bashrc" }
        - { src: "{{ home_dir }}/.dotfiles/.p10k.zsh", path: "{{ home_dir }}/.p10k.zsh" }
        - { src: "{{ home_dir }}/.dotfiles/.profile", path: "{{ home_dir }}/.profile" }
        - { src: "{{ home_dir }}/.dotfiles/.tmux.conf", path: "{{ home_dir }}/.tmux.conf" }
        - { src: "{{ home_dir }}/.dotfiles/.zshrc", path: "{{ home_dir }}/.zshrc" }
        - { src: "{{ home_dir }}/.dotfiles/.config/nvim", path: "{{ home_dir }}/.config/nvim" }

  tasks:
    - name: Erstellen von Symlinks für Konfigurationsdateien
      become: yes
      block:
        - name: Stelle sicher, dass das Zielverzeichnis existiert
          file:
            path: "{{ item.path | dirname }}"
            state: directory
            mode: '0755'
          loop: "{{ symlink_list }}"

        - name: Erstelle Symlink
          file:
            src: "{{ item.src }}"
            dest: "{{ item.path }}"
            state: link
            force: yes
          loop: "{{ symlink_list }}"
    
    - name: Installieren von grundlegenden Programmen
      become: yes
      dnf:
        name: 
          - make
          - npm
          - go
          - rust
          - cargo
          - tmux
          - zsh
          - ranger
          - pip
          - neovim
        state: present

    - name: Install go dependencies
      become: yes
      shell: go install {{ item }}@latest
      loop:
        - mvdan.cc/sh/v3/cmd/shfmt
        - gitlab.com/gitlab-org/cli/cmd/glab
        - github.com/Gelio/go-global-update
        - golang.org/x/tools/gopls
        - golang.org/x/lint/golint
        - golang.org/x/tools/cmd/goimports
      environment:
        GOPATH: /path/to/your/gopath

    - name: Install rust dependencies
      become: yes
      community.general.cargo:
        name: "{{ item }}"
        state: present
      loop:
        - atuin
        - cargo-updater
        - git-delta
        - ripgrep
        - fd-find

    - name: "nerd-fonts: repository"
      git:
        repo: "https://github.com/ryanoasis/nerd-fonts.git"
        dest: "{{ home_dir }}/workspace/other/nerd-fonts"
        depth: 1
        clone: yes

    - name: "nerd-fonts: install"
      command: bash -c './install.sh'
      args:
        chdir: "{{ home_dir }}/workspace/other/nerd-fonts"
    - name: Clone packer.nvim repository into the specified directory
      git:
        repo: 'https://github.com/wbthomason/packer.nvim'
        dest: '~/.local/share/nvim/site/pack/packer/start/packer.nvim'
        version: 'HEAD'
        depth: 1
